name: Build CLI
on:
  push:
  pull_request:
  release:
    types: [published]

env:
  TAG: ${{ github.ref }}

jobs:
# Common Build matrix for builds on Ubuntu Lasted VM

  ubuntu_now_build:
    name: ${{ matrix.build_name }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        # Add more compilers here if you need them
        #build_name: ['Ubuntu 24.04']
        include:
          - build_name: 'Ubuntu 22.04 - GCC'
            package_name: 'gcc g++'
            cc: gcc
            cxx: g++
            label: ubuntu-22.04
            deployable: true

    env:
      CCACHE_DIR: $GITHUB_WORKSPACE/.ccache
      LABEL: ${{ matrix.label }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive


      # Fetch Dependencies
      - name: Dependencies
        run: |
          sudo apt update
          sudo apt upgrade
          sudo apt-get install -y build-essential python3-dev curl autotools-dev libicu-dev libbz2-dev cmake git screen checkinstall zlib1g-dev ${{ matrix.package_name }}

      # Install Boost
      - name: Install Boost
        run: |
          curl -fL -o boost_1_84_0.tar.bz2 https://archives.boost.io/release/1.84.0/source/boost_1_84_0.tar.bz2
          tar -xjf boost_1_84_0.tar.bz2
          cd boost_1_84_0
          ./bootstrap.sh --with-libraries=system,filesystem,thread,date_time,chrono,regex,serialization,atomic,program_options,locale,timer,log
          ./b2
          cd ..
          echo export BOOST_ROOT=/home/runner/work/pdc/pdc/boost_1_84_0 .bashrc

      # Install OpenSSL
      - name: Install OpenSSL
        run: |
          curl -fL -o openssl-1.1.1w.tar.gz https://github.com/openssl/openssl/releases/download/OpenSSL_1_1_1w/openssl-1.1.1w.tar.gz
          tar xaf openssl-1.1.1w.tar.gz
          cd openssl-1.1.1w/
          ./config --prefix=/home/runner/work/pdc/pdc/openssl --openssldir=/home/runner/work/pdc/pdc/openssl shared zlib
          make
          make install
          cd ..

      # Install Ccache
      - name: Setup ccache
        run: |
          sudo apt install ccache

      # Retrieve ccache
      - name: Retrieve ccache
        uses: actions/cache@v4
        with:
          path: .ccache
          key: ccache-${{ matrix.label }}

     # Configure the project with cmake
      - name: Configure
        env:
          CC: ${{ matrix.cc }}
          CXX: ${{ matrix.cxx }}
        run: |
          mkdir build && cd build
          cmake  -D BOOST_ROOT=/home/runner/work/pdc/pdc/boost_1_84_0 -D OPENSSL_ROOT_DIR=/home/runner/work/pdc/pdc/openssl -D BUILD_GUI=OFF -D STATIC=true -D CMAKE_BUILD_TYPE=Release -D BUILD_TESTS=OFF ..

      # Build for linux
      - name: Build
        run: |
          cd build
          make

      # Prepare for deploy
      - name: Prepare for Deploy
        id: before_deploy
        env:
          COMMIT_SHA: ${{ github.sha }}
        run: |
          if [[ "${TAG:5:4}" == "tags" ]]; then export TAG=${TAG:10}; else export TAG=${COMMIT_SHA}; fi
          cd build/src
          TARGETS="pdcd connectivity_tool simplewallet"
          if [[ "${LABEL}" != "aarch64" ]]; then strip ${TARGETS}; fi
          rm -rf Pdc-${TAG}
          mkdir Pdc-${TAG}
          cp ${TARGETS} Pdc-${TAG}/
          tar cvfz Pdc-${TAG}-${LABEL}.tar.gz Pdc-${TAG}/

      # Upload to GH Release
      - name: Upload to GH Release
        if: github.event_name == 'release' && matrix.deployable
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/src/Pdc-${{ github.event.release.tag_name }}-${{ env.LABEL }}.tar.gz
          asset_name: Pdc-${{ github.event.release.tag_name }}-${{ env.LABEL }}.tar.gz
          asset_content_type: application/gzip

      # Upload to GH Actions Artifacts
      - name: Upload To GH Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Pdc-${{ github.sha }}-${{ env.LABEL }}
          path: ./build/src/Pdc-${{ github.sha }}


  # Mac builds on Catalina VM
  macos_build:
    name: macOS
    runs-on: macos-14
    env:
      LABEL: osx
      CCACHE_DIR: $GITHUB_WORKSPACE/.ccache
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      # Fetch Dependencies
      - name: Dependencies
        run: |
          brew install --force ccache cmake openssl@3

      # Install Boost
      - name: Install Boost
        run: |
          curl -fL -o boost_1_84_0.tar.bz2 https://archives.boost.io/release/1.84.0/source/boost_1_84_0.tar.bz2
          tar -xjf boost_1_84_0.tar.bz2
          cd boost_1_84_0
          ./bootstrap.sh
          ./b2
          cd ..

      # Retrieve ccache
      - name: Retrieve ccache
        uses: actions/cache@v4
        with:
          path: .ccache
          key: ccache-osx

      # Configure project with cmake
      - name: Configure
        run: |
          mkdir build && cd build
          cmake -D BOOST_ROOT=${{ github.workspace }}/boost_1_84_0 -D BOOST_LIBRARYDIR=${{ github.workspace }}/boost_1_84_0/stage/lib -D OPENSSL_ROOT_DIR=/opt/homebrew/opt/openssl@3 -D BUILD_GUI=OFF -D CMAKE_BUILD_TYPE=Release -D BUILD_TESTS=OFF ..

      # Build for macOS
      - name: Build
        run: |
          cd build
          make

       # Prepare for deploy
      - name: Prepare for Deploy
        id: before_deploy
        env:
          COMMIT_SHA: ${{ github.sha }}
        run: |
          if [[ "${TAG:5:4}" == "tags" ]]; then export TAG=${TAG:10}; else export TAG=${COMMIT_SHA}; fi
          cd build/src
          TARGETS="pdcd connectivity_tool simplewallet"
          if [[ "${LABEL}" != "aarch64" ]]; then strip ${TARGETS}; fi
          rm -rf Pdc-${TAG}
          mkdir Pdc-${TAG}
          cp ${TARGETS} Pdc-${TAG}/
          tar cvfz Pdc-${TAG}-${LABEL}.tar.gz Pdc-${TAG}/

      # Upload to GH Release
      - name: Upload to GH Release
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/src/Pdc-${{ github.event.release.tag_name }}-${{ env.LABEL }}.tar.gz
          asset_name: Pdc-${{ github.event.release.tag_name }}-${{ env.LABEL }}.tar.gz
          asset_content_type: application/gzip

      # Upload to GH Actions Artifacts
      - name: Upload To GH Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Pdc-${{ github.sha }}-${{ env.LABEL }}
          path: ./build/src/Pdc-${{ github.sha }}


  # Windows 10
  windows_build:
    name: Windows
    runs-on: windows-latest
    env:
      MSBUILD_PATH: "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/MSBuild/Current/Bin"
      LABEL: windows
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      # Setup clcache
      - name: Setup clcache
        run: pip install clcache

      # Retrieve clcache
      - name: Retrieve clcache
        uses: actions/cache@v4
        with:
          path: clcache
          key: clcache-windows

      # Install OpenSSH
      - name: Install OpenSSL
        run: choco install openssl -y

      # Install boost
      - name: Install Boost 1.82.0
        run: |
          $link = "https://boost.teeks99.com/bin/1.82.0/boost_1_82_0-msvc-14.3-64.exe"
          $path = "C:\boost.exe"
          [Net.WebClient]::new().DownloadFile($link, $path)
          Start-Process C:\boost.exe -ArgumentList "/DIR=C:\local\boost_1_82_0","/VERYSILENT" -Wait
          Get-ChildItem C:\local\boost_1_82_0

      # Configure project with cmake
      - name: Configure
        run: |
          mkdir build
          cd build
          cmake -G "Visual Studio 17 2022" -A x64 -T host=x64 .. -DBUILD_GUI=OFF -D BOOST_ROOT=C:/local/boost_1_82_0 -D BOOST_LIBRARYDIR="C:/local/boost_1_82_0/lib64-msvc-14.3" -D OPENSSL_ROOT_DIR="C:/Program Files/OpenSSL-Win64" -D STATIC=OFF

      # Build for Windows
      - name: Build
        run: |
          $env:CLCACHE_DIR = "$env:GITHUB_WORKSPACE\clcache"
          $env:PATH = "$env:PATH;$env:MSBUILD_PATH"
          cd build
          dir
          MSBuild Pdc.sln /p:Configuration=Release /t:Build

      # Prepare for deploy
      - name: Prepare for Deploy
        shell: bash
        id: before_deploy
        env:
          COMMIT_SHA: ${{ github.sha }}
        run: |
          if [[ "${TAG:5:4}" == "tags" ]]; then export TAG=${TAG:10}; else export TAG=${COMMIT_SHA}; fi
          cd build/src/Release
          rm -rf Pdc-${TAG}
          mkdir Pdc-${TAG}
          cp *.exe Pdc-${TAG}/
          7z a Pdc-${TAG}-${LABEL}.zip Pdc-${TAG}/

      # Upload to GH Release
      - name: Upload to GH Release
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/src/Release/Pdc-${{ github.event.release.tag_name }}-${{ env.LABEL }}.zip
          asset_name: Pdc-${{ github.event.release.tag_name }}-${{ env.LABEL }}.zip
          asset_content_type: application/zip

      # Upload to GH Actions Artifacts
      - name: Upload To GH Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Pdc-${{ github.sha }}-${{ env.LABEL }}
          path: ./build/src/Release/Pdc-${{ github.sha }}
