name: Build GUI
on:
  push:
  pull_request:
  release:
    types: [published]

env:
  TAG: ${{ github.ref }}

jobs:

# Common Build matrix for builds on Ubuntu Lasted VM
  ubuntu_build:
    name: Ubuntu-2204
    runs-on: self-hosted

    env:
      CCACHE_DIR: $GITHUB_WORKSPACE/.ccache
      LABEL: ${{ matrix.label }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

       # Fetch Dependencies
      - name: Dependencies
        run: |
          sudo apt update
          sudo apt upgrade -y
          sudo apt-get install -y curl build-essential python3-dev autotools-dev libicu-dev libbz2-dev cmake git screen checkinstall zlib1g-dev fuse libfuse2 libxcb-xinerama0 gcc g++

      # Install Boost
#      - name: Install Boost
#        run: |
#          curl -OL https://boostorg.jfrog.io/artifactory/main/release/1.84.0/source/boost_1_84_0.tar.bz2
#          tar -xjf boost_1_84_0.tar.bz2
#          cd boost_1_84_0
#          ./bootstrap.sh --with-libraries=system,filesystem,thread,date_time,chrono,regex,serialization,atomic,program_options,locale,timer,log
#          ./b2
#          cd ..
#          echo export BOOST_ROOT= ${{ github.workspace }}/zano/zano/boost_1_84_0 .bashrc

      # Install OpenSSH
#      - name: Install OpenSSL
#        run: |
#          curl -OL https://www.openssl.org/source/openssl-1.1.1n.tar.gz
#          tar xaf openssl-1.1.1n.tar.gz
#          cd openssl-1.1.1n/
#          ./config --prefix= /home/arek/actions-runner-pdc/_work/Zano/Zano/openssl --openssldir= /home/arek/actions-runner-pdc/_work/Zano/Zano/openssl shared zlib
#          make
#          make install
#          cd ..

      # Setup Ccache
      - name: Setup ccache
        run: |
          sudo apt install ccache

      # Install Qt
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: '==3.1.*'
          version: '5.12.12'
          host: 'linux'
          target: 'desktop'
          arch: 'gcc_64'
          modules: 'debug_info qtcharts qtdatavis3d qtnetworkauth qtpurchasing qtscript qtvirtualkeyboard qtwebengine qtwebglplugin'

      # Retrieve Ccache
      - name: Retrieve ccache
        uses: actions/cache@v1
        with:
          path: .ccache
          key: ccache-${{ matrix.label }}

     # Configure the project with cmake
      - name: Configure
        env:
          CC: ${{ matrix.cc }}
          CXX: ${{ matrix.cxx }}
        run: |
          mkdir build && cd build
          cmake -D STATIC=TRUE -D ARCH=x86-64 -D CMAKE_PREFIX_PATH= ${{ github.workspace }}/Zano/Qt/5.12.12/gcc_64 -D BUILD_GUI=ON -D CMAKE_BUILD_TYPE=Release -D BUILD_TESTS=OFF ..

      # Build for linux
      - name: Build
        run: |
          cd build
          make

      # Prepare for deploy
      - name: Prepare for Deploy
        id: before_deploy
        env:
          COMMIT_SHA: ${{ github.sha }}
        run: |
          if [[ "${TAG:5:4}" == "tags" ]]; then export TAG=${TAG:10}; else export TAG=${COMMIT_SHA}; fi
          prj_root=$(pwd)

          echo Pdc Gui Tar.Gz

          cd build/src
          TARGETS="pdcd connectivity_tool simplewallet"
          if [[ "${LABEL}" != "aarch64" ]]; then strip ${TARGETS}; fi
          rm -rf Zano-Gui-${TAG}
          mkdir Zano-Gui-${TAG}
          cp ${TARGETS} Zano-Gui-${TAG}/
          ls
          cp -r ../../src/gui/qt-daemon/layout/html Zano-Gui-${TAG}/html
          cp ../../utils/buildings/linux/64bit/Zano.sh Zano-Gui-${TAG}/
          cp ../../utils/buildings/linux/64bit/Zano.desktop Zano-Gui-${TAG}/
          chmod 777 Zano-Gui-${TAG}/Zano.desktop
          chmod 777 Zano-Gui-${TAG}/Zano.sh
          mkdir Zano-Gui-${TAG}/lib
          cp /home/runner/work/Zano/Qt/5.12.12/gcc_64/lib/libicudata.so.56 Zano-Gui-${TAG}/lib/
          cp /home/runner/work/Zano/Qt/5.12.12/gcc_64/lib/libicui18n.so.56 Zano-Gui-${TAG}/lib/
          cp /home/runner/work/Zano/Qt/5.12.12/gcc_64/lib/libicuuc.so.56 Zano-Gui-${TAG}/lib/
          cp /home/runner/work/Zano/Qt/5.12.12/gcc_64/lib/libQt5Core.so.5 Zano-Gui-${TAG}/lib/
          cp /home/runner/work/Zano/Qt/5.12.12/gcc_64/lib/libQt5DBus.so.5 Zano-Gui-${TAG}/lib/
          cp /home/runner/work/Zano/Qt/5.12.12/gcc_64/lib/libQt5Gui.so.5 Zano-Gui-${TAG}/lib/
          cp /home/runner/work/Zano/Qt/5.12.12/gcc_64/lib/libQt5Network.so.5 Zano-Gui-${TAG}/lib/
          cp /home/runner/work/Zano/Qt/5.12.12/gcc_64/lib/libQt5OpenGL.so.5 Zano-Gui-${TAG}/lib/
          cp /home/runner/work/Zano/Qt/5.12.12/gcc_64/lib/libQt5Positioning.so.5 Zano-Gui-${TAG}/lib/
          cp /home/runner/work/Zano/Qt/5.12.12/gcc_64/lib/libQt5PrintSupport.so.5 Zano-Gui-${TAG}/lib/
          cp /home/runner/work/Zano/Qt/5.12.12/gcc_64/lib/libQt5Qml.so.5 Zano-Gui-${TAG}/lib/
          cp /home/runner/work/Zano/Qt/5.12.12/gcc_64/lib/libQt5Quick.so.5 Zano-Gui-${TAG}/lib/
          cp /home/runner/work/Zano/Qt/5.12.12/gcc_64/lib/libQt5Sensors.so.5 Zano-Gui-${TAG}/lib/
          cp /home/runner/work/Zano/Qt/5.12.12/gcc_64/lib/libQt5Sql.so.5 Zano-Gui-${TAG}/lib/
          cp /home/runner/work/Zano/Qt/5.12.12/gcc_64/lib/libQt5Widgets.so.5 Zano-Gui-${TAG}/lib/
          cp /home/runner/work/Zano/Qt/5.12.12/gcc_64/lib/libQt5WebEngine.so.5 Zano-Gui-${TAG}/lib/
          cp /home/runner/work/Zano/Qt/5.12.12/gcc_64/lib/libQt5WebEngineCore.so.5 Zano-Gui-${TAG}/lib/
          cp /home/runner/work/Zano/Qt/5.12.12/gcc_64/lib/libQt5WebEngineWidgets.so.5 Zano-Gui-${TAG}/lib/
          cp /home/runner/work/Zano/Qt/5.12.12/gcc_64/lib/libQt5WebChannel.so.5 Zano-Gui-${TAG}/lib/
          cp /home/runner/work/Zano/Qt/5.12.12/gcc_64/lib/libQt5XcbQpa.so.5 Zano-Gui-${TAG}/lib/
          cp /home/runner/work/Zano/Qt/5.12.12/gcc_64/lib/libQt5QuickWidgets.so.5 Zano-Gui-${TAG}/lib/
          cp /home/runner/work/Zano/Qt/5.12.12/gcc_64/libexec/QtWebEngineProcess Zano-Gui-${TAG}/
          cp /home/runner/work/Zano/Qt/5.12.12/gcc_64/resources/qtwebengine_resources.pak Zano-Gui-${TAG}/
          cp /home/runner/work/Zano/Qt/5.12.12/gcc_64/resources/qtwebengine_resources_100p.pak Zano-Gui-${TAG}/
          cp /home/runner/work/Zano/Qt/5.12.12/gcc_64/resources/qtwebengine_resources_200p.pak Zano-Gui-${TAG}/
          cp /home/runner/work/Zano/Qt/5.12.12/gcc_64/resources/icudtl.dat Zano-Gui-${TAG}/
          cp /home/runner/work/Zano/Qt/5.12.12/gcc_64/resources/qtwebengine_devtools_resources.pak Zano-Gui-${TAG}/
          mkdir Zano-Gui-${TAG}/lib/platforms
          cp /home/runner/work/Zano/Qt/5.12.12/gcc_64/plugins/platforms/libqxcb.so Zano-Gui-${TAG}/lib/platforms/
          mkdir Zano-Gui-${TAG}/xcbglintegrations
          cp /home/runner/work/Zano/Qt/5.12.12/gcc_64/plugins/xcbglintegrations/libqxcb-glx-integration.so Zano-Gui-${TAG}/xcbglintegrations
          tar cvfz Zano-Gui-${TAG}-${LABEL}.tar.gz Zano-Gui-${TAG}/

          echo Zano GUI AppImage

          rm -rf Zano-GUI-${TAG}
          mkdir Zano-GUI-${TAG}
          mkdir -p Zano-GUI-${TAG}/usr/bin
          mkdir -p Zano-GUI-${TAG}/usr/lib
          mkdir -p Zano-GUI-${TAG}/usr/share/applications
          mkdir -p Zano-GUI-${TAG}/usr/share/icons/hicolor/scalable/apps
          mkdir -p Zano-GUI-${TAG}/usr/share/icons/hicolor/256x256/apps
          cp -r ../../src/gui/qt-daemon/layout/html Zano-GUI-${TAG}/usr/bin/
          cp ${TARGETS} Zano-GUI-${TAG}/usr/bin/
          ls
          cp ../../utils/buildings/linux/64bit/Zano.desktop Zano-GUI-${TAG}/usr/share/applications/Zano.desktop
          cp ../../resources/app_icon.svg Zano-GUI-${TAG}/usr/share/icons/hicolor/scalable/apps/Zano.svg
          cp ../../resources/app_icon_256.png Zano-GUI-${TAG}/usr/share/icons/hicolor/256x256/apps/Zano.png
          echo "Exec=$prj_root/build/src/Zano-GUI-${TAG}/usr/bin/Zano" >> Zano-GUI-${TAG}/usr/share/applications/Zano.desktop
          rm -rf /home/runner/work/_temp/
          wget https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
          chmod 777 linuxdeployqt-continuous-x86_64.AppImage
          /home/runner/work/Zano/Zano/build/src/linuxdeployqt-continuous-x86_64.AppImage ./Zano-GUI-${TAG}/usr/share/applications/Zano.desktop -qmake=/home/runner/work/Zano/Qt/5.12.12/gcc_64/bin/qmake
          wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod 777 appimagetool-x86_64.AppImage
          rm -rf Zano-GUI-${TAG}/AppRun
          cp ../../utils/buildings/linux/64bit/Zano_appimage_wrapper.sh Zano-GUI-${TAG}/AppRun
          chmod 777 Zano-GUI-${TAG}/*
          chmod 777 Zano-GUI-${TAG}/*/*
          chmod 777 Zano-GUI-${TAG}/*/*/*
          chmod 777 Zano-GUI-${TAG}/*/*/*/*
          chmod 777 Zano-GUI-${TAG}/*/*/*/*/*
          ARCH=x86_64 /home/runner/work/Zano/Zano/build/src/appimagetool-x86_64.AppImage ./Zano-GUI-${TAG} Zano-GUI-${TAG}-${LABEL}.AppImage

      # Upload to GH Release
      - name: Upload to GH Release
        if: github.event_name == 'release' && matrix.deployable
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/src/Zano-Gui-${{ github.event.release.tag_name }}-${{ env.LABEL }}.tar.gz
          asset_name: Zano-Gui-${{ github.event.release.tag_name }}-${{ env.LABEL }}.tar.gz
          asset_content_type: application/gzip

      # Upload to GH Release
      - name: Upload to GH Release
        if: github.event_name == 'release' && matrix.deployable
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/src/Zano-GUI-${{ github.event.release.tag_name }}-${{ env.LABEL }}.AppImage
          asset_name: Zano-GUI-${{ github.event.release.tag_name }}-${{ env.LABEL }}.AppImage
          asset_content_type: application/octet-stream

      # Upload to GH Actions Artifacts
      - name: Upload To GH Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Zano-Gui-${{ github.sha }}-${{ env.LABEL }}
          path: ./build/src/Zano-Gui-${{ github.sha }}

      # Upload to GH Actions Artifacts AppData
      - name: Upload To GH Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Zano-GUI-${{ github.sha }}-${{ env.LABEL }}.AppImage
          path: ./build/src/Zano-GUI-${{ github.sha }}-${{ env.LABEL }}.AppImage


 # Mac builds on Catalina VM
  macos_build:
    name: macOS
    runs-on: macos-13
    env:
      LABEL: osx
      CC: /usr/local/opt/llvm@15/bin/clang
      CXX: /usr/local/opt/llvm@15/bin/clang++
      CCACHE_DIR: $GITHUB_WORKSPACE/.ccache
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      # Fetch Dependencies
      - name: Dependencies
        run: |
          brew install --force ccache llvm@15 cmake

       # Install Boost
      - name: Install Boost
        run: |
          curl -OL https://boostorg.jfrog.io/artifactory/main/release/1.80.0/source/boost_1_80_0.tar.bz2
          tar -xjf boost_1_80_0.tar.bz2
          cd boost_1_80_0
          ./bootstrap.sh
          ./b2
          cd ..

      # Retrieve ccache
      - name: Retrieve ccache
        uses: actions/cache@v1
        with:
          path: .ccache
          key: ccache-osx

       # Install Qt
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: '==3.1.*'
          version: '5.12.12'
          host: 'mac'
          target: 'desktop'
          arch: 'clang_64'
          modules: 'debug_info qtcharts qtdatavis3d qtnetworkauth qtpurchasing qtscript qtvirtualkeyboard qtwebengine qtwebglplugin'

      # Configure project with cmake
      - name: Configure
        run: |
          mkdir build && cd build
          cmake -D BOOST_ROOT=/Users/runner/work/Zano/Zano/boost_1_80_0 -D BOOST_LIBRARYDIR=/Users/runner/work/Zano/Zano/boost_1_80_0/stage/lib  -D OPENSSL_ROOT_DIR=/usr/local/opt/openssl -D CMAKE_PREFIX_PATH=/Users/runner/work/Zano/Qt/5.12.12/clang_64 -D BUILD_GUI=ON -D CMAKE_BUILD_TYPE=Release -D BUILD_TESTS=OFF ..

      # Build for macOS
      - name: Build
        run: |
          cd build
          make

       # Prepare for deploy
      - name: Prepare for Deploy
        id: before_deploy
        env:
          COMMIT_SHA: ${{ github.sha }}
        run: |
          if [[ "${TAG:5:4}" == "tags" ]]; then export TAG=${TAG:10}; else export TAG=${COMMIT_SHA}; fi
          cd build/src
          TARGETS="pdcd connectivity_tool simplewallet"
          if [[ "${LABEL}" != "aarch64" ]]; then strip ${TARGETS}; fi
          rm -rf Zano-Gui-${TAG}
          mkdir Zano-Gui-${TAG}
          cp ${TARGETS} Zano-Gui-${TAG}/
          tar cvfz Zano-Gui-${TAG}-${LABEL}.tar.gz Zano-Gui-${TAG}/

      # Upload to GH Release
      - name: Upload to GH Release
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/src/Zano-Gui-${{ github.event.release.tag_name }}-${{ env.LABEL }}.tar.gz
          asset_name: Zano-Gui-${{ github.event.release.tag_name }}-${{ env.LABEL }}.tar.gz
          asset_content_type: application/gzip

      # Upload to GH Actions Artifacts
      - name: Upload To GH Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Zano-Gui-${{ github.sha }}-${{ env.LABEL }}
          path: ./build/src/Zano-Gui-${{ github.sha }}



  # Windows 10
  windows_build:
    name: Windows
    runs-on: windows-latest
    env:
      MSBUILD_PATH: "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/MSBuild/Current/Bin"
      LABEL: windows
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      # Install Clcache
      - name: Setup clcache
        run: pip install clcache

      # Checkout repository and submodules
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      # Retrive Clcache
      - name: Retrieve clcache
        uses: actions/cache@v1
        with:
          path: clcache
          key: clcache-windows

      # Install OpenSSL
      - name: Install OpenSSL
        run: choco install openssh

      # Install QT
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.12.12'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2017_64'
          modules: 'debug_info qtcharts qtdatavis3d qtnetworkauth qtpurchasing qtscript qtvirtualkeyboard qtwebengine qtwebglplugin'

      # Install boost
      - name: Install Boost 1.82.0
        run: |
          $link = "https://boost.teeks99.com/bin/1.82.0/boost_1_82_0-msvc-14.3-64.exe"
          $path = "C:\boost.exe"
          [Net.WebClient]::new().DownloadFile($link, $path)
          Start-Process C:\boost.exe -ArgumentList "/DIR=C:\local\boost_1_82_0","/VERYSILENT" -Wait
          Get-ChildItem C:\local\boost_1_82_0

      # Configure project with cmake
      - name: Configure
        run: |
          mkdir build
          cd build
          cmake -G "Visual Studio 17 2022" -A x64 -T host=x64 .. -DBUILD_GUI=ON -D CMAKE_PREFIX_PATH=D:\a\Zano\Qt\5.12.12\msvc2017_64 -D BOOST_ROOT=C:/local/boost_1_82_0 -D BOOST_LIBRARYDIR="C:/local/boost_1_82_0/lib64-msvc-14.1"  -D OPENSSL_ROOT_DIR="C:/Program Files/OpenSSL" -D STATIC=OFF
          dir

      # Build for Windows
      - name: Build
        run: |
          $env:CLCACHE_DIR = "$env:GITHUB_WORKSPACE\clcache"
          $env:PATH = "$env:PATH;$env:MSBUILD_PATH"
          cd build
          dir
          MSBuild Pdc.sln /p:Configuration=Release /t:Build

      # Prepare for deploy
      - name: Prepare for Deploy
        shell: bash
        id: before_deploy
        env:
          COMMIT_SHA: ${{ github.sha }}
        run: |
          if [[ "${TAG:5:4}" == "tags" ]]; then export TAG=${TAG:10}; else export TAG=${COMMIT_SHA}; fi
          cd build/src/Release
          rm -rf Zano-Gui-${TAG}
          mkdir Zano-Gui-${TAG}
          dir
          cp Pdc.exe Zano-Gui-${TAG}/
          D:/a/Zano/Qt/5.12.12/msvc2017_64/bin/windeployqt.exe Zano-Gui-${TAG}/Pdc.exe
          cp -r ../../../src/gui/qt-daemon/layout/html Zano-Gui-${TAG}/html
          7z a Zano-Gui-${TAG}-${LABEL}.zip Zano-Gui-${TAG}
        #  cp ../../../utils/buildings/windows/64bit/setup_64.iss Zano-Gui-${TAG}
        #  cp ../../../utils/buildings/windows/64bit/vc_redist.x64.exe Zano-Gui-${TAG}

      # Upload to GH Release
      - name: Upload to GH Release
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/src/Release/Zano-Gui-${{ github.event.release.tag_name }}-${{ env.LABEL }}.zip
          asset_name: Zano-Gui-${{ github.event.release.tag_name }}-${{ env.LABEL }}.zip
          asset_content_type: application/zip

      # Upload to GH Actions Artifacts
      - name: Upload To GH Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Zano-Gui-${{ github.sha }}-${{ env.LABEL }}
          path: ./build/src/Release/Zano-Gui-${{ github.sha }}

      # Compile .ISS to .EXE Installer - No Release
      - name: Compile .ISS to .EXE Installer - No Release
        if: github.event_name != 'release' && !(startsWith(github.ref, 'refs/tags/'))
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: build/src/Release/Zano-Gui-${{ github.sha }}/setup_64.iss
          options: /O+ /DBinariesPath=..\Zano-Gui-${{ github.sha }} /O..\Zano\build\src\Release /FZano-Gui-${{ github.sha }}-${{ env.LABEL }}

      # Compile .ISS to .EXE Installer - Release
      - name: Compile .ISS to .EXE Installer - Release
        if: github.event_name == 'release' && startsWith(github.ref, 'refs/tags/')
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: build/src/Release/Zano-Gui-${{ github.event.release.tag_name }}/setup_64.iss
          options: /O+ /DBinariesPath=..\Zano-Gui-${{ github.event.release.tag_name }} /O..\Zano\build\src\Release /FZano-Gui-${{ github.event.release.tag_name }}-${{ env.LABEL }}

      # Upload to GH Actions Artifacts EXE
      - name: Upload To GH Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Zano-Gui-${{ github.sha }}-${{ env.LABEL }}.exe
          path: ./build/src/Release/Zano-Gui-${{ github.sha }}-${{ env.LABEL }}.exe

      # Upload to GH Release EXE
      - name: Upload to GH Release
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/src/Release/Zano-Gui-${{ github.event.release.tag_name }}-${{ env.LABEL }}.exe
          asset_name: Zano-Gui-${{ github.event.release.tag_name }}-${{ env.LABEL }}.exe
          asset_content_type: application/octet-stream
